name: Feature Build


on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create local properties
        run: echo -e "LIFT_API_URL=$LIFT_API_URL\nLIFT_S3_URL=$LIFT_S3_URL" >> ./local.properties
        env:
          LIFT_API_URL: ${{secrets.LIFT_API_URL}}
          LIFT_S3_URL: ${{secrets.LIFT_S3_URL}}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Test
        run: ./gradlew testDebugUnitTest
  send-slack:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: send slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          if_mention: failure,cancelled
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SEND_SLACK }}

