name: Feature Build


on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - 'feature/**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build


  send-slack:
    runs-on: ubuntu-latest
    needs: build
    uses: rtCamp/action-slack-notify@v2.0.0
    env:
      SLACK_COLOR: '#00FF00'
      SLACK_TITLE: 'FEATURE Build'
      SLACK_TEXT: 'The build and deployment process has been completed successfully.'
      SLACK_WEBHOOK: ${{ secrets.SEND_SLACK }}

